name: 'Unit Tests Action'
description: 'Run unit tests using pytest with configurable parameters'

inputs:
  os:
    description: 'Operating system to run tests on'
    required: true
  env:
    description: 'Python environment to use (e.g., py310, py311, py313)'
    required: true
  test_access_type:
    description: 'Test access type (public or private)'
    required: true
    default: 'public'
  test_type:
    description: 'Type of test to run (e.g., unittests, integration)'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Install Pixi
      uses: prefix-dev/setup-pixi@v0.8.8
      with:
        environments: ${{ inputs.env }}
        pixi-version: v0.46.0
        cache: true
    - name: Run pytest
      env:
        GITHUB_TOKEN: ${{ secrets.MEDIMG_TESTDATA_PAT }}
        GH_TOKEN: ${{ secrets.MEDIMG_TESTDATA_PAT }}
        TEST_DATASET_TYPE: ${{ inputs.test_access_type }}
      run: |
        # specifically run code-coverage for py313 public ubuntu tests
        if [[ "${{ inputs.os }}" == "ubuntu-latest" && "${{ inputs.env }}" == "py313" && "${{ inputs.test_access_type }}" == "public" ]]; then
          pixi run -e ${{ inputs.env }} ${{ inputs.test_type }}_cov
        else
          pixi run -e ${{ inputs.env }} ${{ inputs.test_type }}
        fi
      shell: bash

    # TODO:: reintroduce coverage report upload
    - name: Use Codecov to track coverage
      if: inputs.os == 'ubuntu-latest' && inputs.env == 'py313' && inputs.test_access_type == 'public'
      uses: codecov/codecov-action@v3
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage-report/coverage.xml
          verbose: true
          name: codecov-umbrella

    - name: JUnit Test Summary
      id: pytest-summary
      if: failure()
      uses: test-summary/action@v2
      with: 
        paths: .cache/test-results/**/*.xml
        show: "fail,skip"