[tool.coverage.run]
omit = [
    "src/imgtools/loggers/**/*.py",
    "src/imgtools/cli/**/*.py",
    "tests/**/*.py",
    "src/imgtools/datasets/sample_images.py", # take forever on GHA
]

[tool.coverage.report]
