name: Termshot PNG Test

on:
    workflow_dispatch:
    pull_request:
        branches:
            - development
            - 'jjjermiah/*'

jobs:
  generate-png:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            url: https://github.com/homeport/termshot/releases/download/v0.5.0/termshot_0.5.0_linux_amd64.tar.gz
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download and install termshot
        run: |
          curl -L "${{ matrix.url }}" -o termshot.tar.gz
          tar -xzf termshot.tar.gz
          chmod +x termshot
          sudo mv termshot /usr/local/bin/termshot

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          environments: "py313" 
          pixi-version: v0.46.0
          cache: true
          activate-environment: true

      - name: Install the project
        run: imgtools --help

      - name: Generate PNG using termshot
        run: |
          mkdir -p output
          termshot --show-cmd --filename output/screenshot.png -- uvx --from 'med-imagetools[all]' --prerelease=allow imgtools --help

      - name: Upload PNG artifact
        uses: actions/upload-artifact@v4
        with:
          name: termshot-png-${{ runner.os }}
          path: output/screenshot.png